server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: infolog
    static_configs:
      - targets:
          - localhost
        labels:
          job: infolog
          __path__: /appeals/info/infolog.log

  - job_name: infolog_management
    static_configs:
      - targets:
          - localhost
        labels:
          job: infolog_management
          __path__: /managment/info/infolog.log
